### ISSUE TITLE
worker nodes fail to join cluster

### ISSUE THREAD

**Issue by pkelleratwork** [WesleyCharlesBlake/terraform-aws-eks#12]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.
follow instructions, encountered no errors. worker nodes fail to connect to cluster after running `kubectl apply -f config-map-aws-auth.yaml`

**Input Code**
- REPL or Repo link if applicable:

```js
var your => (code) => here;
```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code). worker nodes connect

**Environment**
- Terraform version - v0.11.11
- AWS Region us-east-1
- OS: [e.g. OSX 10.13.4, Windows 10] Mojave 10.14.3
- How you are using using the eks-terraform module: per instructions in readme

**Possible Solution**

**Additional context
Add any other context about the problem here. If applicable, add screenshots to help explain.
```(⎈ aws:)➜  zoo ✗ kubectl get configmaps -n kube-system
NAME                                 DATA   AGE
aws-auth                             1      8m
coredns                              1      13m
extension-apiserver-authentication   5      13m
kube-proxy                           1      13m```

```(⎈ aws:)➜  zoo ✗ kubectl describe configmap aws-auth -n kube-system
Name:         aws-auth
Namespace:    kube-system
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::xxxx:role/moon-eks-node-role\n  username: system:node:{{EC2PrivateD...

Data
====
mapRoles:
----
- rolearn: arn:aws:iam::xxxx:role/moon-eks-node-role
  username: system:node:{{EC2PrivateDNSName}}
  groups:
    - system:bootstrappers
    - system:nodes

Events:  <none>```

**Comment by WesleyCharlesBlake** [comment]
Thanks for this. I will be looking into this asap

**Comment by WesleyCharlesBlake** [comment]
The latest release [v2.0.0](releases/tag/v2.0.0) should solve this issue.

Make sure that you applied the config map, and can verify that the config map resource exists in your cluster. This is the only thing that will stop your nodes from joining the cluster
