### ISSUE TITLE
How to setup public and private subnet ?

### ISSUE THREAD

**Issue by davistran86** [WesleyCharlesBlake/terraform-aws-eks#13]
Hi there,
I would like to deploy the cluster with private and public subnet, how can I do it with your script ? Thanks a lot :)

**Comment by rplute** [comment]
Yes, the README is advertised it provisions a public and private subnet, but it doesn't actually provision a private one.

**Comment by WesleyCharlesBlake** [comment]
The latest release [v2.0.0](releases/tag/v2.0.0) adds support for private subnets.
