### ISSUE TITLE
Timeout when using kubectl logs or kubectl exec

### ISSUE THREAD

**Issue by infinitydon** [WesleyCharlesBlake/terraform-aws-eks#14]
## Bug Report

**Current Behavior**
After terraform finishes creating the kubernetes cluster, PODs are in-accessible either by using "kubectl logs or kubectl exec"

Sample error output:

Error: forwarding ports: error upgrading connection: error dialing backend: dial tcp 172.22.31.213:10250: getsockopt: no route to host

**Expected behavior/code**
kubectl calls to PODs should not be timing out.

**Environment**
- Terraform version: v0.11.13
- AWS Region: eu-central-1
- OS: Ubuntu 18.04.1 LTS
- How you are using using the eks-terraform module: terraform apply

**Possible Solution**
Update the locals section of eks-worker-nodes.tf according to terraform EKS documentation so as to properly bootstrap the AWS EKS AMI. 
I will also try to create a PR

**Comment by Weyker** [comment]
I change the eks-worker-nodes.tf file, on locals { node-userdata = ...
to this:

```
# EKS currently documents this required userdata for EKS worker nodes to
# properly configure Kubernetes applications on the EC2 instance.
# We utilize a Terraform local here to simplify Base64 encoding this
# information into the AutoScaling Launch Configuration.
# More information: https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-06-05/amazon-eks-nodegroup.yaml
locals {
  node-userdata = <<USERDATA
#!/bin/bash -xe
/etc/eks/bootstrap.sh --b64-cluster-ca '${aws_eks_cluster.eks.certificate_authority.0.data}' --apiserver-endpoint '${aws_eks_cluster.eks.endpoint}' '${var.cluster-name}'
USERDATA
}
```
and solve the problem.

**Comment by infinitydon** [comment]
Yes.. I already opened a PR for this also..

**Comment by bcouetil** [comment]
Thanks, I had the same issue, and after a few hours of searching, came here.

Please merge the PR 😃
