### ISSUE TITLE
MissingClusterDNS when deploy application

### ISSUE THREAD

**Issue by dearteno** [WesleyCharlesBlake/terraform-aws-eks#17]
## Bug Report
MissingClusterDNS when deploy application
**Current Behavior**
 
```kubelet does not have ClusterDNS IP configured and cannot create Pod using "ClusterFirst" policy. Falling back to "Default" policy.```

**Expected behavior/code**
A clear and concise description of what you expected to happen (or code).

**Environment**
- Terraform version  v0.11.13
- AWS Region ap-southeast-1
- OS: [e.g. OSX 10.13.4, Windows 10] MacOS 10.14.4
- How you are using using the eks-terraform module:
'aws', 'EKS'

**Comment by wired-R** [comment]
+1

**Comment by wired-R** [comment]
https://github.com/WesleyCharlesBlake/terraform-aws-eks/pull/16 
this resolve issue

**Comment by WesleyCharlesBlake** [comment]
The latest release [v2.0.0](releases/tag/v2.0.0) fixes this
