### ISSUE TITLE
Error: Unsupported block type, modules\eks\vpc.tf, modules\eks\eks-cluster.tf

### ISSUE THREAD

**Issue by jasonlll88** [WesleyCharlesBlake/terraform-aws-eks#18]
## Bug Report

**Current Behavior**
When I run terraform validate command Error: Unsupported block type appear

**Input Code**

```js
terraform validate

Error: Unsupported block type

  on modules\eks\eks-cluster.tf line 44, in resource "aws_security_group" "cluster":
  44:   tags {

Blocks of type "tags" are not expected here. Did you mean to define argument
"tags"? If so, use the equals sign to assign it a value.


Error: Unsupported block type

  on modules\eks\vpc.tf line 38, in resource "aws_internet_gateway" "eks":
  38:   tags {
```

**Expected behavior/code**

**Environment**
- Terraform version Terraform v0.12.0
- AWS Region us-east-2
- OS: [Windows 10 using gitbash]
- How you are using using the eks-terraform module:
git clone from this repository

**Possible Solution**

tags {} should be change for  tags = {}

**Comment by WesleyCharlesBlake** [comment]
This is a compatibility issue with Terraform 0.12 >

There wereajor changes to the way that Terraform handles variables and assignments from < 0.11. I have a fix for this which will be pushed soon

**Comment by sratcleartax** [comment]
@jasonlll88, simply putting it like 
tag = {} will work.

**Comment by WesleyCharlesBlake** [comment]
The latest release [v2.0.0](releases/tag/v2.0.0)  fixes this and sorts out issues with terraform 0.12 >
