### ISSUE TITLE
error while destroying cluster

### ISSUE THREAD

**Issue by aliartiza75** [WesleyCharlesBlake/terraform-aws-eks#32]
## Bug Report

**Current Behavior**
I created an eks cluster using the provided terraform manifests but the issue is that when I tried to delete the eks cluster it didn't delete the cluster properly. 

I have provided the logs below but the problem with this module is that although the vpc exists but still module wasn't able to delete that cluster properly. 

When I applied the apply operation it showed that the subnets have been created successfully and also in the `terraform.tfstate` file the subnet records exists but when i try to destroy the cluster i get the error given below:

**logs**
```bash
module.eks.module.bastion-asg.aws_launch_configuration.this[0]: Refreshing state... [id=bastion-lc-20190904162029969000X]
module.eks.module.bastion-asg.random_pet.asg_name[0]: Refreshing state... [id=innocent-boa]

Error: no matching subnet found for vpc with id vpc-0fbd66be703dd9102

  on modules/eks/data.tf line 5, in data "aws_subnet_ids" "private":
   5: data "aws_subnet_ids" "private" {



Error: no matching subnet found for vpc with id vpc-0fbd66be703dXXXX

  on modules/eks/data.tf line 13, in data "aws_subnet_ids" "public":
  13: data "aws_subnet_ids" "public" {


Makefile:16: recipe for target 'destroy' failed
make: *** [destroy] Error 1

```

**Input Code**
- REPL or Repo link if applicable:

```js
var your => (code) => here;
```

**Expected behavior/code**
I must have deleted the cluster without any issue. 

**Environment**
- Terraform version: v0.12.7
- AWS Region: eu-west-1
- OS: [e.g. OSX 10.13.4, Windows 10]
- How you are using using the eks-terraform module:

**Possible Solution**

**Additional context
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by aliartiza75** [comment]
@WesleyCharlesBlake kindly have a look this

**Comment by WesleyCharlesBlake** [comment]
hey @aliartiza75 , seems like I had an issue with the way I named VPC resources. This should be resolved with the latest version of the module now.

Thanks for bringing this to my attention.
