### ISSUE TITLE
Document required IAM policies to deploy a cluster

### ISSUE THREAD

**Issue by lazzarello** [WesleyCharlesBlake/terraform-aws-eks#5]
I have attached all EKS policies to my API user. When running a plan I get the following output

```
data.http.workstation-external-ip: Refreshing state...
data.aws_region.current: Refreshing state...
data.aws_ami.eks-worker-ami: Refreshing state...
data.aws_availability_zones.available: Refreshing state...

Error: Error refreshing state: 2 error(s) occurred:

* module.eks.data.aws_ami.eks-worker-ami: 1 error(s) occurred:

* module.eks.data.aws_ami.eks-worker-ami: data.aws_ami.eks-worker-ami: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: bd448f81-8a7a-4a76-8b03-d6e1bca5a1ce
* module.eks.data.aws_availability_zones.available: 1 error(s) occurred:

* module.eks.data.aws_availability_zones.available: data.aws_availability_zones.available: Error fetching Availability Zones: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: 2a4946a3-1cb7-48cd-b5e5-285c7aa35b4a
```

I'll discover the required permissions soon and likely have a PR documenting them.

*Notably, the AWS managed policies for EKS do not permit a user to create an EKS cluster.*

```
* module.eks.aws_eks_cluster.eks: 1 error(s) occurred:

* aws_eks_cluster.eks: error creating EKS Cluster (xxx): AccessDeniedException: User: arn:aws:iam::000000000000:user/xxx is not authorized to perform: eks:CreateCluster on resource: arn:aws:eks:us-west-2:000000000000:cluster/xxx
	status code: 403, request id: 45eaff2f-d872-11e8-818c-956d46f857d3
```

**Comment by abd3** [comment]
Strangely, I'm still getting the errors that @lazzarello shows above, even though I've given my Terraform user's role all of the necessary permissions and even given full Admin access. Any insights into this?
```
Error: Error refreshing state: 2 error(s) occurred:

* module.eks.module.eks.data.aws_availability_zones.available: 1 error(s) occurred:

* module.eks.module.eks.data.aws_availability_zones.available: data.aws_availability_zones.available: Error fetching Availability Zones: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: affa4089-2b56-4aec-8df0-c6f3cf756920
* module.eks.module.eks.data.aws_ami.eks-worker-ami: 1 error(s) occurred:

* module.eks.module.eks.data.aws_ami.eks-worker-ami: data.aws_ami.eks-worker-ami: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: 780756b4-5945-455d-8395-75e5d8bd7951
```

**Comment by abd3** [comment]
OK. I figured out my issue. I have Terraform setup in one AWS account and it is remotely assuming a role in a separate account to control infrastructure. Most of the permissions required to actually set up the cluster need to be applied to the role that is assumed (the target account). But the Terraform data blocks are just lookups to general information on AWS, so I had to give the main Terraform account permission to do the EC2 describe so it could lookup the AMIs. I added just this limited policy to that account:

        - PolicyName: AllowEC2Describe
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'ec2:Describe*'
                Resource: '*'

**Comment by aaronsteers** [comment]
I ran into a similar issue. I created attached a new custom policy with `eks.*` but I was still getting the very misleading message `not authorized to perform: eks:CreateCluster`. Resolved my issue by adding the policy EC2FullAccess - since Terraform will ultimately need to create EC2 instances as well.

**Comment by tigerrabbit** [comment]
Wanted to add one more possible solution if you hit the issue that I did.  What appeared to be a permissions issue was actually being caused because I was using a name that was already in use.  I fixed it by renaming the resource that I was creating to a unique name.  Here is the example I was testing with, https://aws.amazon.com/blogs/startups/from-zero-to-eks-with-terraform-and-helm/".  hope this is helpful to someone.

**Comment by TauseefMalik** [comment]
In my case, I used aws configure initially to setup the account before running terraform commands but I also had a "default" profile in .aws/credentials file which was causing the same error mentioned in the issue. To resolve make sure that the 'default' AWS profile access/secret key is correct.
